### ISSUE TITLE
Downloading sitecore not working: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by vlmironoff** [Sitecore/Sitecore-Instance-Manager#128]
**Importance:**
**Critical** (I need this issue to be fixed)

**Description:**
The issue is that I can't download sitecore via SIM.
I click the ribbon button "Get Sitecore" then Next button then Next again and it throws 'Object Reference not set to the instance of an object' message

LOG INFO:
```
1 14:11:22,137 INFO  **********************************************************************
   1 14:11:22,147 INFO  **********************************************************************
   1 14:11:22,147 INFO  Sitecore Instance Manager started
   1 14:11:22,147 INFO  Version: 1.4.0.383
   1 14:11:22,147 INFO  Revision: rev.160527-1229
   1 14:11:22,147 INFO  Label: 
   1 14:11:22,147 INFO  IsQA: False
   1 14:11:22,147 INFO  Executable: C:\Users\vmi\AppData\Local\Apps\2.0\69847QKM.065\J6WD7R2H.N43\sim...tion_abafaebf7cc9a2b2_0001.0004_9bd46001587f1b56\SIM.Tool.exe
   1 14:11:22,147 INFO  Arguments: child
   1 14:11:22,147 INFO  Directory: C:\Users\vmi\AppData\Local\Apps\2.0\69847QKM.065\J6WD7R2H.N43\sim...tion_abafaebf7cc9a2b2_0001.0004_9bd46001587f1b56
   1 14:11:22,147 INFO  **********************************************************************
   1 14:11:22,147 INFO  **********************************************************************
   1 14:11:22,149 INFO  IIS.Name: World Wide Web Publishing Service
   1 14:11:22,150 INFO  IIS.Status: Running
   1 14:11:22,150 INFO  IIS.MachineName: .
   1 14:11:22,150 INFO  IIS.ServiceName: W3SVC
   1 14:11:22,150 INFO  IIS.ServiceType: Win32ShareProcess
   1 14:11:22,460 ERROR Plugins no longer supported
   1 14:11:25,442 INFO  Wizard pipeline 'download8' starts
   1 14:11:41,777 WARN  The SIM.Tool.Windows.UserControls.ConfirmStepUserControl control does not implement IWizardStep
   1 14:11:46,847 WARN  The SIM.Tool.Windows.UserControls.ConfirmStepUserControl control does not implement IWizardStep
   1 14:11:47,216 INFO  Something went wrong with Wizard logic. It is to be closed. 

Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sitecore.Diagnostics.InformationService.Client.Model.Release.get_DefaultDistributive()
   at Sitecore.Diagnostics.InformationService.Client.Model.Release.get_Downloads()
   at SIM.Tool.Windows.UserControls.Download8.ProductDownload8InCheckbox..ctor(IRelease release)
   at SIM.Tool.Windows.UserControls.Download8.Downloads.<Append>b__a(IRelease r)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SIM.Tool.Windows.UserControls.Download8.Downloads.Append(IEnumerable`1 records)
   at SIM.Tool.Windows.UserControls.Download8.Downloads.InitializeStep(WizardArgs wizardArgs)
   at SIM.Tool.Base.Windows.Wizard.InitializeIWizardStep(Int32 n)
   at SIM.Tool.Base.Windows.Wizard.InitializeStep(Nullable`1 i)
   at SIM.Tool.Base.Windows.Wizard.MoveNextClick(Object sender, RoutedEventArgs e)
  26 14:13:34,990 INFO  Creating folder C:\Users\vmi\AppData\Roaming\Sitecore\Sitecore Instance Manager\Apps\SIMCMD
  26 14:13:51,544 INFO  Unzipping the 'C:\Users\vmi\AppData\Roaming\Sitecore\Sitecore Instance Manager\Apps\SIMCMD\package.zip' archive to the 'C:\Users\vmi\AppData\Roaming\Sitecore\Sitecore Instance Manager\Apps\SIMCMD' folder
   1 14:14:15,799 INFO  Wizard pipeline 'download8' starts
   1 14:14:19,673 WARN  The SIM.Tool.Windows.UserControls.ConfirmStepUserControl control does not implement IWizardStep
   1 14:14:20,808 WARN  The SIM.Tool.Windows.UserControls.ConfirmStepUserControl control does not implement IWizardStep
   1 14:14:21,033 INFO  Something went wrong with Wizard logic. It is to be closed. 

Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sitecore.Diagnostics.InformationService.Client.Model.Release.get_DefaultDistributive()
   at Sitecore.Diagnostics.InformationService.Client.Model.Release.get_Downloads()
   at SIM.Tool.Windows.UserControls.Download8.ProductDownload8InCheckbox..ctor(IRelease release)
   at SIM.Tool.Windows.UserControls.Download8.Downloads.<Append>b__a(IRelease r)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SIM.Tool.Windows.UserControls.Download8.Downloads.Append(IEnumerable`1 records)
   at SIM.Tool.Windows.UserControls.Download8.Downloads.InitializeStep(WizardArgs wizardArgs)
   at SIM.Tool.Base.Windows.Wizard.InitializeIWizardStep(Int32 n)
   at SIM.Tool.Base.Windows.Wizard.InitializeStep(Nullable`1 i)
   at SIM.Tool.Base.Windows.Wizard.MoveNextClick(Object sender, RoutedEventArgs e)
```

**Comment by AlenPelin** [comment]
Should be fixed now.
