### ISSUE TITLE
The remote server returned an error

### ISSUE THREAD

**Issue by ArunkumarKP** [Sitecore/Sitecore-Instance-Manager#148]
Unable to download anything from SIM. Getting below error. Is there a place where we can set proxy details ?
  
######################
  69 02:25:27,155 DEBUG    31.69ms    -  -  -  -  -  Initialization (background thread)
   1 02:25:27,375 DEBUG   252.53ms    -  -  -  -  Long running task
   1 02:25:27,375 DEBUG   253.15ms    -  -  -  Refresh installer
   1 02:25:27,376 DEBUG   259.34ms    -  -  Close wizard
   1 02:25:27,376 DEBUG 1838694.90ms    -  Move next click handler
   1 02:25:34,085 WARN  The http://dl.sitecore.net/updater/1.1/scla/latest-version.txt URL is unavailable
System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
   at System.Net.HttpWebRequest.GetResponse()
   at SIM.WebRequestHelper.RequestAndGetResponse(Uri uri, Nullable`1 timeout, Nullable`1 readWriteTimeout, String cookies)
   at SIM.WebRequestHelper.DownloadString(String url, Nullable`1 timeout, Nullable`1 readWriteTimeout)
   at SIM.Tool.Windows.MainWindowComponents.AbstractDownloadAndRunButton.GetLatestVersion()

#######################

 1 01:54:48,670 DEBUG               -> -> -> -> Initializing step
   1 01:54:48,670 DEBUG                           Caller: SIM.Tool.Base.Windows.Wizard
   1 01:54:48,670 DEBUG                           params n: 1 (System.Int32)
   1 01:54:48,670 DEBUG     0.02ms    -  -  -  -  Initializing step
   1 01:54:48,670 DEBUG     0.28ms    -  -  -  Initializing step
   1 01:54:48,670 DEBUG     0.56ms    -  -  Move back click handler
   1 01:54:48,670 INFO  Something went wrong with Wizard logic. It is to be closed. 

Neither remote service nor its local cache is not available
Sitecore.Diagnostics.InformationService.Client.ServiceNotAvailableException: Neither remote service nor its local cache is not available
   at Sitecore.Diagnostics.InformationService.Client.CacheableObject.GetFilePath(String url)
   at Sitecore.Diagnostics.InformationService.Client.CacheableObject.Get[T](String url)
   at Sitecore.Diagnostics.InformationService.Client.ServiceClient.GetVersions(String productName)
   at SIM.Tool.Windows.UserControls.Download8.DownloadWizardArgs.get_Releases()
   at SIM.Tool.Windows.UserControls.Download8.Downloads.InitializeStep(WizardArgs wizardArgs)
   at SIM.Tool.Base.Windows.Wizard.InitializeIWizardStep(Int32 n)
   at SIM.Tool.Base.Windows.Wizard.InitializeStep(Nullable`1 i)
   at SIM.Tool.Base.Windows.Wizard.MoveNextClick(Object sender, RoutedEventArgs e)

**Comment by AlenPelin** [comment]
It looks like you don't have free internet connection:
```
...
(407) Proxy Authentication Required.
at System.Net.HttpWebRequest.GetResponse()
...
```
