### ISSUE TITLE
SIM failes to authenticate when downloading 6x and 7x

### ISSUE THREAD

**Issue by cassidydotdk** [Sitecore/Sitecore-Instance-Manager#162]
**Importance:**  
Normal (I have a workaround, but it would be nice to fix it)  

**Valid for QA**  
I hereby confirm the issue is reproducible on the latest QA version 1.5.068
which was downloaded today from http://dl.sitecore.net/updater/qa/sim

**Description:**  
I keep getting errors when trying to authenticate to download server for Sitecore 6x and 7x downloads. I used the exact same credentials and they work fine for 8.x downloads.

**Scenario:**  
Using "Bundled Tools" and selecting "Download 6x and 7x"

**Attachments:**  
[2017-05-11.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/992601/2017-05-11.txt)
```

>   23 11:45:00,896 INFO  Long running task "Download Sitecore 6.x and 7.x Wizard" failed with exception
System.InvalidOperationException: The username or password or both are incorrect, or an unexpected error happen
   at SIM.Tool.Windows.UserControls.Download.Login.GetSdnCookie(String username, String password)
   at SIM.Tool.Windows.UserControls.Download.Login.<>c__DisplayClass3_0.<SIM.Tool.Base.Wizards.IFlowControl.OnMovingNext>b__2()
   at SIM.Tool.Base.WindowHelper.<>c__DisplayClass3_2.<LongRunningTask>b__0()
  25 11:45:15,125 INFO  Long running task "Download Sitecore 6.x and 7.x Wizard" failed with exception

**Comment by AlenPelin** [comment]
Download pre-8 functionality is now removed.
