### ISSUE TITLE
SIM Not Supporting Proxy Authentication

### ISSUE THREAD

**Issue by pratz1406** [Sitecore/Sitecore-Instance-Manager#216]
**Description:**  
I am not able to install SIM on my machine

**Scenario:**  
1.  I installed the SIM.Tool.Application
2. I tried to run the application but it failed during checking system requirements stage
3. I work in a corporate office and its mandatory to use a proxy to connect to internet

**Issue is actual**  
I hereby confirm the issue is new

**Valid for QA**  
I hereby confirm the issue is reproducible on the latest SIM.Tool version 1.5
which was downloaded today from http://dl.sitecore.net/updater/qa/sim

**Attachments:**  
PLATFORM VERSION INFO
	Windows 			: 10.0.16299.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.7.2556.0 built by: NET471REL1
	clr.dll 			: 4.7.2556.0 built by: NET471REL1
	dfdll.dll 			: 4.7.2556.0 built by: NET471REL1
	dfshim.dll 			: 10.0.16299.15 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/Users/pr250079/Downloads/SIM.Tool.application
	Deployment Provider url		: http://dl.sitecore.net/updater/sim/SIM.Tool.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\pr250079\Downloads\SIM.Tool.application resulted in exception. Following failure messages were detected:
		+ Downloading http://dl.sitecore.net/updater/sim/SIM.Tool.application did not succeed.
		+ The remote server returned an error: (407) Proxy Authentication Required.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [22/12/2017 14:58:21] : Activation of C:\Users\pr250079\Downloads\SIM.Tool.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [22/12/2017 14:58:21] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading http://dl.sitecore.net/updater/sim/SIM.Tool.application did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirect(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.FollowDeploymentProviderUri(SubscriptionStore subStore, AssemblyManifest& deployment, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- The remote server returned an error: (407) Proxy Authentication Required.
		- Source: System
		- Stack trace:
			at System.Net.HttpWebRequest.GetResponse()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by AlenPelin** [comment]
It is a known issue, check [Prerequisites](https://github.com/Sitecore/Sitecore-Instance-Manager#prerequisites)

**Comment by AlenPelin** [comment]
You should be able to use SIM if you build it from source code though.
