### ISSUE TITLE
Uninstall fails in case 'Install' folder is absent

### ISSUE THREAD

**Issue by AndreyFilchenkov** [Sitecore/Sitecore-Instance-Manager#308]
**Description:**  
The issue is: Uninstall fails in case 'Install' folder is absent

**Scenario:**  
1. Install any topology(e.g. 'sc900xm1');
2. Navigate to the FilesRoot folder and remove 'Sitecore 9.0.0 rev. 171002 (WDP XM1 packages)' folder;
3. Try to delete 'sc900xm1' using SIM;

**Actual result:** 
Uninstall fails with the following exception:
```
   1 08:42:31,989 INFO  Error occured while wizard loading
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Install\SC_Installs\Sitecore 9.0.0 rev. 171002 (WDP XM1 packages)'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at SIM.Sitecore9Installer.Tasker.GetTaskParameters(String name) in C:\Andrey\Tasks\Sitecore-Instance-Manager\src\SIM.Sitecore9Installer\Tasker.cs:line 398
   at SIM.Sitecore9Installer.Tasker..ctor(String unInstallParamsPath) in C:\Andrey\Tasks\Sitecore-Instance-Manager\src\SIM.Sitecore9Installer\Tasker.cs:line 105
   at SIM.Tool.Windows.UserControls.Install.Delete9Details.SIM.Tool.Base.Wizards.IWizardStep.InitializeStep(WizardArgs wizardArgs) in C:\Andrey\Tasks\Sitecore-Instance-Manager\src\SIM.Tool.Windows\UserControls\Delete\Delete9Details.xaml.cs:line 165
   at SIM.Tool.Base.Windows.Wizard.InitializeIWizardStep(Int32 n) in C:\Andrey\Tasks\Sitecore-Instance-Manager\src\SIM.Tool.Base\Windows\Wizard.xaml.cs:line 577
   at SIM.Tool.Base.Windows.Wizard.InitializeStep(Nullable`1 i) in C:\Andrey\Tasks\Sitecore-Instance-Manager\src\SIM.Tool.Base\Windows\Wizard.xaml.cs:line 602
   at SIM.Tool.Base.Windows.Wizard.WindowLoaded(Object sender, RoutedEventArgs e) in C:\Andrey\Tasks\Sitecore-Instance-Manager\src\SIM.Tool.Base\Windows\Wizard.xaml.cs:line 884
```

**Valid for QA**  
Branch: install9
Commit: e1b6252ad82154a007877c2983217b44b417f34e

**Screenshots:**
Please find screenshots attached.
![image](https://user-images.githubusercontent.com/22079019/69491164-f6b40700-0e99-11ea-8da5-2962b465f2de.png)

**Comment by AndreyFilchenkov** [comment]
Fixed via https://github.com/Sitecore/Sitecore-Instance-Manager/pull/313
