### ISSUE TITLE
Enable uninstall 9.3.0

### ISSUE THREAD

**Issue by AndreyFilchenkov** [Sitecore/Sitecore-Instance-Manager#330]
**Tested on:** https://github.com/Sitecore/Sitecore-Instance-Manager/commit/e306eb9efb39a2ce7fb5dc5601549cc5fb539b52

**Steps to reproduce:**
1. Install SC930 xm1;
2. Try to uninstall it;

Uninstall fails due to the following error:
```
   1 22:56:43,369 INFO  Failed to initialize context menu
System.InvalidOperationException: Failed to get databases of C:\inetpub\wwwroot\test201912061925sc930xm1\test201912061925sc930xm1CD.local ---> System.InvalidOperationException: Failed to get web config result of C:\inetpub\wwwroot\test201912061925sc930xm1\test201912061925sc930xm1CD.local ---> System.InvalidOperationException: Failed to build configuration. Reason: An error occurred loading a configuration file: Could not load file or assembly 'Microsoft.Configuration.ConfigurationBuilders.Environment, Version=1.0.0.0, Culture=neutral' or one of its dependencies. The system cannot find the file specified. (C:\inetpub\wwwroot\test201912061925sc930xm1\test201912061925sc930xm1CD.local\web.config line 28)

Server stack trace: 
   at Sitecore.Diagnostics.ConfigBuilder.ConfigEngine.BuildResultConfiguration(String webrootFolder)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Sitecore.Diagnostics.ConfigBuilder.IConfigEngine.BuildResultConfiguration(String webrootFolder)
   at Sitecore.Diagnostics.ConfigBuilder.ConfigBuilderEngine.BuildResultConfigurationXmlString(String webrootFolder) in d:\a\1\s\src\Sitecore.Diagnostics.ConfigBuilder\ConfigBuilderEngine.cs:line 27
   at Sitecore.Diagnostics.ConfigBuilder.ConfigBuilderEngine.BuildShowConfig(String webConfigFilePath) in d:\a\1\s\src\Sitecore.Diagnostics.ConfigBuilder\ConfigBuilderEngine.cs:line 273
   at Sitecore.Diagnostics.ConfigBuilder.ConfigBuilderEngine.BuildWebConfigResult(String webConfigFilePath) in d:\a\1\s\src\Sitecore.Diagnostics.ConfigBuilder\ConfigBuilderEngine.cs:line 244
   at Sitecore.Diagnostics.ConfigBuilder.ConfigBuilderEngine.Build(String webConfigFilePath, Boolean buildWebConfigResult, Boolean normalizeOutput) in d:\a\1\s\src\Sitecore.Diagnostics.ConfigBuilder\ConfigBuilderEngine.cs:line 141
   at SIM.Instances.RuntimeSettings.RuntimeSettingsAccessor.GetWebConfigResult(Boolean normalize) in C:\Andrey\Tasks\Sitecore-Instance-Manager\src\SIM.Instances\RuntimeSettings\RuntimeSettingsAccessor.cs:line 128
   --- End of inner exception stack trace ---
   at SIM.Instances.RuntimeSettings.RuntimeSettingsAccessor.GetWebConfigResult(Boolean normalize) in C:\Andrey\Tasks\Sitecore-Instance-Manager\src\SIM.Instances\RuntimeSettings\RuntimeSettingsAccessor.cs:line 134
   at SIM.Instances.RuntimeSettings.RuntimeSettingsAccessor.GetDatabases() in C:\Andrey\Tasks\Sitecore-Instance-Manager\src\SIM.Instances\RuntimeSettings\RuntimeSettingsAccessor.cs:line 51
   --- End of inner exception stack trace ---
   at SIM.Instances.RuntimeSettings.RuntimeSettingsAccessor.GetDatabases() in C:\Andrey\Tasks\Sitecore-Instance-Manager\src\SIM.Instances\RuntimeSettings\RuntimeSettingsAccessor.cs:line 57
   at SIM.Instances.Instance.GetAttachedDatabases() in C:\Andrey\Tasks\Sitecore-Instance-Manager\src\SIM.Instances\Instance.cs:line 515
   at SIM.Instances.Instance.get_AttachedDatabases() in C:\Andrey\Tasks\Sitecore-Instance-Manager\src\SIM.Instances\Instance.cs:line 70
   at SIM.Pipelines.Delete.DeleteArgs..ctor(Instance instance, SqlConnectionStringBuilder connectionString) in C:\Andrey\Tasks\Sitecore-Instance-Manager\src\SIM.Pipelines\Delete\DeleteArgs.cs:line 44
   at SIM.Tool.Windows.MainWindowComponents.DeleteInstanceButton.OnClick(Window mainWindow, Instance instance) in C:\Andrey\Tasks\Sitecore-Instance-Manager\src\SIM.Tool.Windows\MainWindowComponents\DeleteInstanceButton.cs:line 35
   at SIM.Tool.Windows.MainWindowHelper.<>c__DisplayClass26_0.<InitializeContextMenuItem>b__0(Object obj, RoutedEventArgs e) in C:\Andrey\Tasks\Sitecore-Instance-Manager\src\SIM.Tool.Windows\MainWindowHelper.cs:line 615
```

**Solution:**
We need to upgrade the Sitecore-Diagnostics-Libraries to 2.0.1.171+ version to enable building the configuration of SC.9.3.0. pls see https://github.com/Sitecore/Sitecore-Diagnostics-Libraries/commit/f16d3abf51e1893efd3ec24b54bc3adc97cbd817 for details.

**Comment by AndreyFilchenkov** [comment]
Closed via PR: https://github.com/Sitecore/Sitecore-Instance-Manager/pull/331
