### ISSUE TITLE
ClickOnce installer fails with "Strong name signature not valid for this assembly Microsoft.Management.Infrastructure.dll"

### ISSUE THREAD

**Issue by AndreyFilchenkov** [Sitecore/Sitecore-Instance-Manager#348]
**Description:**  
The issue is: ClickOnce installer fails with "Strong name signature not valid for this assembly Microsoft.Management.Infrastructure.dll"

**Scenario:**  
1. Uninstall SIM QA version from your PC;
2. Try to install the current QA version using page:
http://dl.sitecore.net/updater/qa/sim/

Actual result:
The installation fails with the error:
```
ERROR DETAILS
    Following errors were detected during this operation.
    * [1/17/2020 12:17:10 PM] System.Deployment.Application.InvalidDeploymentException (SignatureValidation)
        - Strong name signature not valid for this assembly Microsoft.Management.Infrastructure.dll.
        - Source: System.Deployment
        - Stack trace:
            at System.Deployment.Application.ComponentVerifier.VerifyStrongNameAssembly(String filePath, AssemblyManifest assemblyManifest)
            at System.Deployment.Application.ComponentVerifier.VerifyComponents()
            at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
            at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
            at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
            at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
            at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
            at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
```

**Issue is actual**  
I hereby confirm the issue is new:
* all [prerequisites](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#prerequisites) are met.
* it is not a [known issue](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#knwon-ssue)
* it was not discussed before (I used GitHub Issues search)

**Valid for QA/DEV**  
I hereby confirm the issue is reproducible on the latest QA/DEV version QA version: **1.6.0.462**

**Comment by AndreyFilchenkov** [comment]
The 'ClickOnce' installer does not support automatic application upgrade in case the "Target Platform" is changed(from x32 to AnyCpu for SIM.Tool project). 

To mitigate the issue:
- new version(1.6) of the tool was released on the new publishing URL. So SIM1.5 is not affected by the issue;
- existing users are able to upgrade SIM version from 1.5 to 1.6 manually.
