### ISSUE TITLE
sitecore-XP1-cm-dds-patch action fails. The term 'nuget' is not recognized.

### ISSUE THREAD

**Issue by sc-ArtemKosohov** [Sitecore/Sitecore-Instance-Manager#352]
**Description:**  
sitecore-XP1-cm-dds-patch action fails. The term 'nuget' is not recognized.

```
ERROR sitecore-XP1-cm-dds-patch action failed with message: Failed to execute sitecore-XP1-cm-dds-patch task. 
System.Management.Automation.CmdletInvocationException: The term 'nuget' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. ---> System.Management.Automation.CommandNotFoundException: The term 'nuget' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at SIM.Sitecore9Installer.Tasks.PowerShellTask.Run() in ...Sitecore-Instance-Manager\src\SIM.Sitecore9Installer\Tasks\PowerShellTask.cs:line 36
```

**Scenario:**  
1. Start installing Sitecore 9.0.2 XP1.
2. Wait until the last task execution.

**Issue is actual**  
I hereby confirm the issue is new:
* all [prerequisites](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#prerequisites) are met.
* it is not a [known issue](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#knwon-ssue)
* it was not discussed before (I used GitHub Issues search)

**Valid for QA/DEV**  
I hereby confirm the issue is reproducible on the latest QA/DEV version SIM DEV 1.6.0.431

**Screenshots:**
Please find screenshots attached.
![Capture](https://user-images.githubusercontent.com/52958875/72893031-b8638880-3d20-11ea-8f3f-6bda9a78ae12.PNG)

**Attachments:**  
Please find attached latest log files from this folders:
[Logs.zip](https://github.com/Sitecore/Sitecore-Instance-Manager/files/4097138/Logs.zip)

**Comment by AndreyFilchenkov** [comment]
Implemented in PR: https://github.com/Sitecore/Sitecore-Instance-Manager/pull/383
