### ISSUE TITLE
System.ArgumentNullException appears if validation skipped by user

### ISSUE THREAD

**Issue by AndreyFilchenkov** [Sitecore/Sitecore-Instance-Manager#434]
**Description:** 
The issue is: ```System.ArgumentNullException``` appears if validation skipped by user
```
Parameter name: source
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at SIM.Tool.Windows.UserControls.Install.Instance9Validation.OnMovingNext(WizardArgs wizardArgs) in ...\Documents\Sitecore-Instance-Manager-test\src\SIM.Tool.Windows\UserControls\Install\Instance9Validation.xaml.cs:line 118
   at SIM.Tool.Base.Windows.Wizard.ProcessStepUserControl(Boolean next) in ...\Documents\Sitecore-Instance-Manager-test\src\SIM.Tool.Base\Windows\Wizard.xaml.cs:line 815
```

**Scenario:**  
1. Click ```Install Sitecore XP 9 and later```  
2. Uncheck ```Validate``` checkbox, click ```Next``` -> ```Yes|No``` -> ```Next``` -> ```Install```

https://www.screencast.com/t/z9Wh0L5pd

**Valid for QA/DEV**  
The issue is reproducible on the latest QA/DEV version:
Commit [8be787b7d8e642f86b2b4894bacbaece00afb4d1]

**Comment by AndreyFilchenkov** [comment]
Fix was merged to:
* rc/1.7
* develop
