### ISSUE TITLE
Unable to reinstall or delete Sitecore XP 8

### ISSUE THREAD

**Issue by DmitryKolinchuk** [Sitecore/Sitecore-Instance-Manager#541]
The following exception occurs when trying to reinstall Sitecore XP 8 instance:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at SIM.Tool.Windows.MainWindowComponents.Buttons.ReinstallInstanceButton.OnClick(Window mainWindow, Instance instance) in C:\GitHub\Sitecore-Instance-Manager\src\SIM.Tool.Windows\MainWindowComponents\Buttons\ReinstallInstanceButton.cs:line 23
   at SIM.Tool.Windows.MainWindowHelper.<>c__DisplayClass27_0.<InitializeContextMenuItem>b__0(Object obj, RoutedEventArgs e) in C:\GitHub\Sitecore-Instance-Manager\src\SIM.Tool.Windows\MainWindowHelper.cs:line 658
```
The following exception occurs when trying to delete Sitecore XP 8 instance:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at SIM.Tool.Base.Windows.Wizard.InitializeStep(Nullable`1 i) in C:\GitHub\Sitecore-Instance-Manager\src\SIM.Tool.Base\Windows\Wizard.xaml.cs:line 681
   at SIM.Tool.Base.Windows.Wizard.MoveNextClick(Object sender, RoutedEventArgs e) in C:\GitHub\Sitecore-Instance-Manager\src\SIM.Tool.Base\Windows\Wizard.xaml.cs:line 772
```

**Comment by AndreyFilchenkov** [comment]
The 'Delete' button also fails as well. It has been tested on SC806
