### ISSUE TITLE
Latest SIM error in Windows 10

### ISSUE THREAD

**Issue by chenhendrawan** [Sitecore/Sitecore-Instance-Manager#55]
I installed SIM via ClickOnce in Windows 10 PC and often get the error below. SIM also doesn't detect Sitecore zip file in my Sitecore repository folder.
Please let me know if you need more information.

   1 14:20:06,452 INFO  Retrieving the COM class factory for component with CLSID {2B72133B-3F5B-4602-8952-803546CE3344} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
System.Runtime.InteropServices.COMException (0x80040154): Retrieving the COM class factory for component with CLSID {2B72133B-3F5B-4602-8952-803546CE3344} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
   at System.Runtime.Remoting.RemotingServices.AllocateUninitializedObject(RuntimeType objectType)
   at System.Runtime.Remoting.Activation.ActivationServices.CreateInstance(RuntimeType serverType)
   at System.Runtime.Remoting.Activation.ActivationServices.IsCurrentContextOK(RuntimeType serverType, Object[] props, Boolean bNewObj)
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at Microsoft.Web.Administration.ConfigurationManager.CreateAdminManager[TClass,TInterface](WebConfigurationMap webConfigMap, Boolean isAdminConfig)
   at Microsoft.Web.Administration.ConfigurationManager.CreateConfiguration(WebConfigurationMap configMap, String configPathToEdit, Boolean isAdminConfig)
   at Microsoft.Web.Administration.ConfigurationManager.GetConfiguration(String rawConfigurationPath, String cacheKey, Boolean isAdminConfig)
   at Microsoft.Web.Administration.ConfigurationManager.GetApplicationHostConfiguration()
   at Microsoft.Web.Administration.ServerManager.get_SitesSection()
   at Microsoft.Web.Administration.ServerManager.get_Sites()
   at SIM.Instances.InstanceManager.GetOperableSites(WebServerContext context, String defaultRootFolder, Nullable`1 detectEverywhere)
   at SIM.Instances.InstanceManager.Initialize(String defaultRootFolder)
   at SIM.Tool.Windows.MainWindowHelper.RefreshInstances()
   at SIM.Tool.Windows.MainWindowHelper.Initialize()
   at SIM.Tool.Windows.MainWindow.WindowLoaded(Object sender, EventArgs eventArgs)

**Comment by AlenPelin** [comment]
IIS installed?

**Comment by AlenPelin** [comment]
Added IIS status check during initialization in 82b54a4 (1.4.0.227)

Reopen this issue if the problem persists.

**Comment by chenhendrawan** [comment]
You absolutely correct. IIS was not installed. This is embarrassing for me :D I just installed everything on new Windows 10 pc, and forgot to install IIS.
Thanks for your help anyway.

**Comment by AlenPelin** [comment]
Totally understandable. Thanks to you, since now this kind of error will not be reproduced ever :sunglasses:
