### ISSUE TITLE
Open in Browser fails

### ISSUE THREAD

**Issue by IvanSheyenko** [Sitecore/Sitecore-Instance-Manager#559]
1. install sitecore 8.x
2. select open sitecore client on the last step

Result:
error occurs
10:15:29,038 INFO  The Open in Browser (Sitecore Client) finish action has thrown an exception
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at SIM.Instances.InstanceManager.GetInstance(String name) in C:\pss\sim\src\SIM.Instances\InstanceManager.cs:line 118
   at SIM.Tool.Base.Pipelines.InstallWizardArgs.get_Instance() in C:\pss\sim\src\SIM.Tool.Base\Pipelines\InstallWizardArgs.cs:line 51
   at SIM.Tool.Windows.Pipelines.Install.InstallActions.OpenSitecoreClient(InstallWizardArgs args) in C:\pss\sim\src\SIM.Tool.Windows\Pipelines\Install\InstallActions.cs:line 52
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at SIM.Tool.Base.Windows.Wizard.WindowClosed(Object sender, EventArgs e) in C:\pss\sim\src\SIM.Tool.Base\Windows\Wizard.xaml.cs:line 950

**Comment by DmitryKolinchuk** [comment]
The issue occurs in the 'SIM.Instances.InstanceManager.GetInstance' method due to the following change that was introduced in scope of the [https://github.com/Sitecore/Sitecore-Instance-Manager/commit/b7c3fe55fe381244e253e4fa9d53e19d23ee0a06#diff-7d8bf828f341c34aaa04e06eff8a84bf9cae0f57fa454744895b58795abd4b4c](https://github.com/Sitecore/Sitecore-Instance-Manager/commit/b7c3fe55fe381244e253e4fa9d53e19d23ee0a06#diff-7d8bf828f341c34aaa04e06eff8a84bf9cae0f57fa454744895b58795abd4b4c) commit:
```
if (Instances == null)
{
  Initialize();
}
```
In this case, the newly created instance is not added to the collection and the following code below throws the exception:
`return PartiallyCachedInstances?[name];
`
