### ISSUE TITLE
No LDF files

### ISSUE THREAD

**Issue by RobAhnemann** [Sitecore/Sitecore-Instance-Manager#56]
I'm not sure why, but when I create a new site, the LDF files are not being extracted into the Databases folder.  I checked if they were in the zip, and they surely are.  This is causing the DBs not to attach. Is there some log file I can view to see what is happening?

Thanks!

**Comment by AlenPelin** [comment]
SIM ignores LDF files to speed up installation. This is possible as LDF files are re-created automatically during attaching the database to SQL Server.

There is a SIM Logs button in Bundled Tools.

**Comment by RobAhnemann** [comment]
Thanks for the quick reply, that's good to know.  I was looking through the logs, and I saw this:

 14 09:57:58,866 INFO  Attaching the 'ClientSitecore_core' database with 'D:\Publish\SIM\Client\Databases\Sitecore.core.mdf' filename
  14 09:57:58,871 INFO  SQL query is executed: create database [ClientSitecore_core] on (filename = N'D:\Publish\SIM\Client\Databases\Sitecore.core.mdf') for attach
  14 09:57:59,077 WARN  Attaching reporting.secondary database failed. Skipping...
System.Data.SqlClient.SqlException (0x80131904): Cannot create file 'D:\SQL\2008\Data\Sitecore.core_log.LDF' because it already exists. Change the file path or the file name, and retry the operation.
Could not open new database 'ClientSitecore_core'. CREATE DATABASE is aborted.
File activation failure. The physical file name "D:\SB\Foundation.Content\Tracking_8.1_U1\build\dist\Sitecore 8.1 rev. 151207\Databases\Sitecore.core.LDF" may be incorrect.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at SIM.Adapters.SqlServer.SqlServerManager.Execute(SqlConnection sqlConnection, String command, Nullable`1 executionTimeout)
   at SIM.Adapters.SqlServer.SqlServerManager.AttachDatabase(String name, String path, SqlConnectionStringBuilder connectionString, Boolean attachLog)
   at SIM.Pipelines.AttachDatabasesHelper.AttachDatabase(String name, String databasesFolderPath, ConnectionString connectionString, SqlConnectionStringBuilder defaultConnectionString, IPipelineController controller)
   at SIM.Pipelines.AttachDatabasesHelper.AttachDatabase(ConnectionString connectionString, SqlConnectionStringBuilder defaultConnectionString, String name, String databasesFolderPath, String instanceName, IPipelineController controller)
ClientConnectionId:484876a6-489d-48ab-8fed-260af4827fe2

It looks like it's trying to put the LDF file in the default SQL location, not in the same place as the MDF files.  I already have that file there, so it's erroring out. Is it possible to configure it to drop the LDF files in the same place as the MDF files?

Thanks!

**Comment by AlenPelin** [comment]
I cannot reproduce this locally, but we should be able to fix that.

**Comment by mcongdon** [comment]
Wanted to chime in as I have the exact same issue. SIM installs the log files in the default location configured in SQL server with the same names- so it works for the first install- but will get the above error if you try installing a another instance.

**Comment by AlenPelin** [comment]
The issue should not be actual when the RenameSqlFiles advanced setting is enabled (SIM 1.5). Could anybody confirm?

**Comment by DmitryKolinchuk** [comment]
Closed since the issue is outdated.
