### ISSUE TITLE
The "Cannot mix synchronous and asynchronous operation on process stream." error may occur while deploying to Docker

### ISSUE THREAD

**Issue by DmitryKolinchuk** [Sitecore/Sitecore-Instance-Manager#677]
The following error may occur while deploying to Docker:
```
Processor of type 'SIM.Pipelines.Install.Containers.RunDockerProcessor' failed. Cannot mix synchronous and asynchronous operation on process stream.
System.InvalidOperationException: Cannot mix synchronous and asynchronous operation on process stream.
   at System.Diagnostics.Process.get_StandardError()
   at SIM.Pipelines.BaseProcessors.RunCmdCommandBaseProcessor.RunCommand(String executionFolder, String command) in C:\GitHub\Sitecore-Instance-Manager\src\SIM.Pipelines\BaseProcessors\RunCmdCommandBaseProcessor.cs:line 49
   at SIM.Pipelines.BaseProcessors.RunCmdCommandBaseProcessor.Process(ProcessorArgs procArgs) in C:\GitHub\Sitecore-Instance-Manager\src\SIM.Pipelines\BaseProcessors\RunCmdCommandBaseProcessor.cs:line 29
   at SIM.Pipelines.Processors.Processor.Execute(ProcessorArgs args) in C:\GitHub\Sitecore-Instance-Manager\src\SIM.Base\Pipelines\Processors\Processor.cs:line 137
```
Looks like this may occur due to the following code:
```
proc.OutputDataReceived += Proc_DataReceived;
proc.ErrorDataReceived += Proc_DataReceived;
```

Similar issue is mentioned in the following resources:
[https://stackoverflow.com/questions/36487532/c-sharp-system-invalidoperationexception-cannot-mix-synchronous-and-asynchrono](https://stackoverflow.com/questions/36487532/c-sharp-system-invalidoperationexception-cannot-mix-synchronous-and-asynchrono)
[https://coder.gay/450069/invalidoperationexception-synchronous-asynchronous-operation](https://coder.gay/450069/invalidoperationexception-synchronous-asynchronous-operation)

**Comment by DmitryKolinchuk** [comment]
Close as it is duplicate of the following issue:
[https://github.com/Sitecore/Sitecore-Instance-Manager/issues/667](https://github.com/Sitecore/Sitecore-Instance-Manager/issues/667)
