### ISSUE TITLE
"is not a valid project name" error occurs when deploying Sitecore using the latest Docker version

### ISSUE THREAD

**Issue by DmitryKolinchuk** [Sitecore/Sitecore-Instance-Manager#732]
**Scenario:**  
1. Install the latest Docker version.
2. Deploy, for example, SC 10.3 to Docker (the "Include topology and tag to the project name" checkbox on the second step must be selected).
**Result:** the following error occurs:
```
Processor of type 'SIM.Pipelines.Install.Containers.RunDockerBuildProcessor' failed. Failed to run 'docker-compose.exe build --no-cache' in 'C:\inetpub\wwwroot\sc103'
System.AggregateException: Failed to run 'docker-compose.exe build --no-cache' in 'C:\inetpub\wwwroot\sc103'
   at SIM.Pipelines.BaseProcessors.RunCmdCommandBaseProcessor.RunCommand(String executionFolder, String command)
   at SIM.Pipelines.BaseProcessors.RunCmdCommandBaseProcessor.Process(ProcessorArgs procArgs)
   at SIM.Pipelines.Processors.Processor.Execute(ProcessorArgs args)'
```
**Details:**
If to run the "docker-compose.exe build --no-cache" command from PowerShell then the following error occurs:
`"sc103-xm1-10.3-ltsc2019" is not a valid project name: it must contain only characters from [a-z0-9_-] and start with [a-z0-9]`
The following Docker version was used:
![image](https://github.com/Sitecore/Sitecore-Instance-Manager/assets/20965100/b3c9c671-9749-4316-b64d-a4102a370795)
The issue is also described here: `https://github.com/docker/compose/issues/9216`

**Comment by DmitryKolinchuk** [comment]
The validation to the Project Name field should be also added (it must contain only characters from [a-z0-9_-] and start with [a-z0-9]).
