### ISSUE TITLE
Could not load file or assembly 'System.Threading.Tasks

### ISSUE THREAD

**Issue by KayeeNL** [Sitecore/Sitecore-Instance-Manager#76]
Hi @AlenPelin ,

I was just looking through the SIM logs of the new version, (update-3) and saw the following errors. seems that assembly 'System.Threading.Tasks is missing on the application? 

```
An error occurred during retrieving current domain name
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.DirectoryServices.ActiveDirectory.ActiveDirectoryOperationException: Current security context is not associated with an Active Directory domain or forest.
   at System.DirectoryServices.ActiveDirectory.DirectoryContext.GetLoggedOnDomain()
   at System.DirectoryServices.ActiveDirectory.DirectoryContext.IsContextValid(DirectoryContext context, DirectoryContextType contextType)
   at System.DirectoryServices.ActiveDirectory.DirectoryContext.isDomain()
   at System.DirectoryServices.ActiveDirectory.Domain.GetDomain(DirectoryContext context)
   at SIM.Tool.Base.EnvironmentHelper.<GetIsSitecoreMachine>b__5()
   at SIM.Tool.Base.EnvironmentHelper.<>c__DisplayClassa`1.<Run>b__9(Object param0)
   --- End of inner exception stack trace ---
   at SIM.Tool.Base.EnvironmentHelper.Run[T](TimeSpan timeout, Func`1 operation)
   at SIM.Tool.Base.EnvironmentHelper.GetIsSitecoreMachine()
   1 13:46:57,752 INFO  Error in app insights
System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Tasks, Version=2.6.8.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Threading.Tasks, Version=2.6.8.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

   at Microsoft.ApplicationInsights.Channel.FlushManager.Flush()
   at Microsoft.ApplicationInsights.Channel.PersistenceChannel.Flush()
   at SIM.Tool.Base.Analytics.Start()
```

Next error:
```
10 13:46:58,568 WARN  The Path: Plugins, Recursive: True manifest lookup folder doesn't exist
   8 13:47:19,438 INFO  Generating NuGet packages for C:\Users\robberthock\Documents\SIM Repository\Sitecore 8.1 rev. 160302.zip
   8 13:47:31,577 INFO  Generating NuGet packages for C:\Users\robberthock\Documents\SIM Repository\Sitecore 8.1 rev. 160519.zip
   1 13:47:46,152 INFO  Error during flushing
System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Tasks, Version=2.6.8.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Threading.Tasks, Version=2.6.8.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

   at Microsoft.ApplicationInsights.Channel.FlushManager.Flush()
   at Microsoft.ApplicationInsights.Channel.PersistenceChannel.Flush()
   at SIM.Tool.Base.Analytics.Flush()
```

**Comment by AlenPelin** [comment]
Thanks @KayeeNL for reporting this. It should be fixed now in the next QA build.

**Comment by AlenPelin** [comment]
The first issue (SIM.Tool.Base.EnvironmentHelper.GetIsSitecoreMachine) seems to be coming from very old version of SIM. 

Please supply me with the entire SIM log file.

**Comment by KayeeNL** [comment]
[2016-05-26.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/285157/2016-05-26.txt)
[2016-05-26_DEBUG.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/285158/2016-05-26_DEBUG.txt)

hereby the log file @AlenPelin 

regards
Robbert

**Comment by KayeeNL** [comment]
Hi @AlenPelin ,

working on a Mac, installed Windows 10 through a Parallells VM:

OS Name	Microsoft Windows 10 Home
Version	10.0.10586 Build 10586
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	ROBBERTHOCKF86C
System Manufacturer	Parallels Software International Inc.
System Model	Parallels Virtual Platform
System Type	x64-based PC
System SKU	Undefined
Processor	Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz, 2494 Mhz, 4 Core(s), 4 Logical Processor(s)
BIOS Version/Date	Parallels Software International Inc. 11.2.0 (32581), 27-Apr-16

**Comment by AlenPelin** [comment]
As I mentioned before, you are using Update-2 released in Feb. This issue should be already fixed in latest 373 build. I believe you run SIM via shortcut (pinned to taskbar) which may not fire ClickOnce update. Try `press Win -> type SIM -> press Enter` or use this link: http://dl.sitecore.net/updater/sim

```
   1 13:46:57,298 INFO  Version: 1.4.0.227
   1 13:46:57,298 INFO  Revision: rev.160229-623
```

**Comment by KayeeNL** [comment]
@AlenPelin 

Strange, it did update to the newest version (saw the clickonce dialog popping up). Removed my SIM logs, and restarted SIM, installed a new Sitecore instance, and generated new NuGet packages, I don't see any SIM logs created however now. 

Guess this isn;t an issue anymore ;-)

--Robbert

**Comment by KayeeNL** [comment]
@AlenPelin 

I do run it from the taskbar yes
