### ISSUE TITLE
Error when trying to open Config Builder from inside SIM

### ISSUE THREAD

**Issue by shanidgafur** [Sitecore/Sitecore-Instance-Manager#91]
Keep getting an error when trying to open Config builder from inside SIM. There is a "Plugins no longer supported" error message in the log files followed by a stack trace. Details below..

```   
   1 12:48:18,283 ERROR Plugins no longer supported
   1 12:48:24,854 INFO  Error during handling menu button click: SIM.Tool.Windows.MainWindowComponents.ConfigBuilderButton
System.NullReferenceException: Object reference not set to an instance of an object.
   at SIM.Core.CoreApp.<RunApp>b__4(String x)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at SIM.Core.CoreApp.RunApp(String app, String[] params)
   at SIM.Tool.Windows.MainWindowComponents.AbstractDownloadAndRunButton.RunApp(String path, String param)
   at SIM.Tool.Windows.MainWindowComponents.AbstractDownloadAndRunButton.RunApp(Window mainWindow, String param)
   at SIM.Tool.Windows.MainWindowComponents.ConfigBuilderButton.OnClick(Window mainWindow, Instance instance)
   at SIM.Tool.Windows.MainWindowHelper.<>c__DisplayClass19.<GetRibbonButton>b__15(Object param0, RoutedEventArgs param1)
   1 12:48:55,626 INFO  Error during handling menu button click: SIM.Tool.Windows.MainWindowComponents.ConfigBuilderButton
System.NullReferenceException: Object reference not set to an instance of an object.
   at SIM.Core.CoreApp.<RunApp>b__4(String x)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at SIM.Core.CoreApp.RunApp(String app, String[] params)
   at SIM.Tool.Windows.MainWindowComponents.AbstractDownloadAndRunButton.RunApp(String path, String param)
   at SIM.Tool.Windows.MainWindowComponents.AbstractDownloadAndRunButton.RunApp(Window mainWindow, String param)
   at SIM.Tool.Windows.MainWindowComponents.ConfigBuilderButton.OnClick(Window mainWindow, Instance instance)
   at SIM.Tool.Windows.MainWindowHelper.<>c__DisplayClass19.<GetRibbonButton>b__15(Object param0, RoutedEventArgs param1)
```

**Comment by AlenPelin** [comment]
Please supply entire log file.

**Comment by shanidgafur** [comment]
[2016-06-16.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/318575/2016-06-16.txt)
[2016-06-16_DEBUG.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/318574/2016-06-16_DEBUG.txt)

**Comment by AlenPelin** [comment]
This should be already fixed in QA.
http://dl.sitecore.net/updater/qa/sim
